-- Run this once in your Supabase project's SQL Editor (see config.js for
-- the full step-by-step). Select all of this file's text, paste it into
-- a New Query, then click Run.

-- The table that holds every shared homework assignment.
create table assignments (
    id bigint generated by default as identity primary key,
    title text not null,
    subject text not null,
    due timestamptz not null,
    est_hours numeric,
    completed boolean not null default false,
    added_by text,
    created_at timestamptz not null default now()
);

-- Row Level Security must be ON for the public policies below to apply.
alter table assignments enable row level security;

-- These four policies allow anyone holding the anon key (i.e. anyone with
-- this app's config.js) to read and write freely, with no login. See the
-- "Security note" in config.js before relying on this for anything sensitive.
create policy "public read" on assignments for select using (true);
create policy "public insert" on assignments for insert with check (true);
create policy "public update" on assignments for update using (true);
create policy "public delete" on assignments for delete using (true);

-- Enables live updates: without this, changes only show up for other
-- people after they refresh the page instead of instantly. (This is
-- what the dashboard's old "Database -> Replication" per-table toggle
-- used to do — running it here works no matter how that page looks now.)
alter publication supabase_realtime add table assignments;
